version: '2'

services:
  chai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chai
    environment:
      JDBC_URL: jdbc:postgresql://foodgen-db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: mysecretpassword
    ports:
      - '9000:9000'

  foodgen-db:
    image: postgres:latest
    container_name: foodgen-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./src/test/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
