---
  swagger: "2.0"
  info:
    title: "FoodGen API"
    description: "Endpoints for the FoodGen Application"
    version: "1.0.0"
  consumes:
    - application/json
  produces:
    - application/json